FROM nginx:1.19.0-alpine

# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d
# COPY nginx.conf /etc/nginx/nginx.conf


# # django
# FROM python:3.6

# ENV PYTHONUNBUFFERED 1

# WORKDIR /backend

# COPY requirements.txt requirements.txt

# RUN pip3 install -r /backend/requirements.txt

# # COPY .Django .

# ADD . .

# EXPOSE 8000